CREATE EVENT update_promotion_date
ON SCHEDULE EVERY 1 MONTH
STARTS (CURRENT_DATE + INTERVAL 1 DAY - INTERVAL DAYOFMONTH(CURRENT_DATE) DAY)
DO
  UPDATE
    promotions
  SET 
    start_at = DATE_FORMAT(CURRENT_DATE - INTERVAL DAYOFMONTH(CURRENT_DATE) - 1 DAY, '%Y-%m-01'),
    end_at = LAST_DAY(CURRENT_DATE)
  WHERE
    id = 1;
